import { collection, doc, writeBatch, setDoc } from "firebase/firestore";
import { db } from "./firebase";
import { Category, Difficulty, Role } from "./types";

const challenges = [
  {
    challengeId: "reusable-bottle-day",
    title: "Reusable Bottle Day",
    description: "Carry and use a reusable water bottle all day to reduce single-use plastic waste.",
    shortDescription: "Carry and use a reusable water bottle all day.",
    category: Category.WATER,
    difficulty: Difficulty.EASY,
    points: 10,
    bonusPointsStreak: 5,
    iconEmoji: "💧",
    bannerImageUrl: "https://picsum.photos/seed/bottle/800/400",
    proofInstructions: "Upload a photo of your reusable bottle in hand or on your desk.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "short-shower",
    title: "Short Shower Challenge",
    description: "Take a shower under 5 minutes to conserve water.",
    shortDescription: "Take a shower under 5 minutes.",
    category: Category.WATER,
    difficulty: Difficulty.MEDIUM,
    points: 15,
    bonusPointsStreak: 5,
    iconEmoji: "🚿",
    bannerImageUrl: "https://picsum.photos/seed/shower/800/400",
    proofInstructions: "Upload a photo of a timer showing <5:00 next to running water.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "lights-out",
    title: "Lights Out Hour",
    description: "Turn off all non-essential lights for 1 hour to save energy.",
    shortDescription: "Turn off all non-essential lights for 1 hour.",
    category: Category.ENERGY,
    difficulty: Difficulty.EASY,
    points: 10,
    bonusPointsStreak: 5,
    iconEmoji: "💡",
    bannerImageUrl: "https://picsum.photos/seed/lights/800/400",
    proofInstructions: "Upload a photo of your dark room or only essential light.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "walk-it",
    title: "Walk It",
    description: "Walk instead of taking a vehicle for any trip under 1 km.",
    shortDescription: "Walk instead of taking a vehicle for short trips.",
    category: Category.TRANSPORT,
    difficulty: Difficulty.EASY,
    points: 15,
    bonusPointsStreak: 5,
    iconEmoji: "🚶",
    bannerImageUrl: "https://picsum.photos/seed/walk/800/400",
    proofInstructions: "Upload a walking selfie or a Google Maps screenshot showing your walk.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "no-plastic-bag",
    title: "No Plastic Bag",
    description: "Carry a cloth or reusable bag for all your shopping today.",
    shortDescription: "Carry a cloth/reusable bag for all shopping.",
    category: Category.WASTE,
    difficulty: Difficulty.EASY,
    points: 10,
    bonusPointsStreak: 5,
    iconEmoji: "🛍️",
    bannerImageUrl: "https://picsum.photos/seed/bag/800/400",
    proofInstructions: "Upload a photo of your cloth bag with your purchases.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "fix-the-drip",
    title: "Fix the Drip",
    description: "Inspect all faucets, hoses, and flush tanks in your home and fix or report any persistent leaks.",
    shortDescription: "Find and fix or report household faucet leaks.",
    category: Category.WATER,
    difficulty: Difficulty.MEDIUM,
    points: 20,
    bonusPointsStreak: 5,
    iconEmoji: "🔧",
    bannerImageUrl: "https://picsum.photos/seed/leakfix/800/400",
    proofInstructions: "Upload a photo of the repaired tap, washer replacement, or dry sink basin.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "bucket-car-wash",
    title: "Bucket Over Hose Vehicle Wash",
    description: "Wash your bicycle, two-wheeler, or car using a bucket and sponge instead of a running water hose.",
    shortDescription: "Clean your vehicle using a single bucket of water.",
    category: Category.WATER,
    difficulty: Difficulty.EASY,
    points: 15,
    bonusPointsStreak: 5,
    iconEmoji: "🪣",
    bannerImageUrl: "https://picsum.photos/seed/bucketwash/800/400",
    proofInstructions: "Upload a photo of your bucket, sponge, and clean vehicle without a running hose.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "rainwater-catchment-check",
    title: "Rainwater Harvest Catchment",
    description: "Set up or inspect a rainwater collection barrel or runoff diversion pipe for garden irrigation.",
    shortDescription: "Set up or inspect a rainwater collection container.",
    category: Category.WATER,
    difficulty: Difficulty.HARD,
    points: 35,
    bonusPointsStreak: 10,
    iconEmoji: "🌧️",
    bannerImageUrl: "https://picsum.photos/seed/rainbarrel/800/400",
    proofInstructions: "Upload a photo of your rainwater collection drum or gutter connection.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "aerator-upgrade",
    title: "Install Tap Aerator",
    description: "Install a low-flow faucet aerator or water restrictor to reduce tap flow by up to 50 percent.",
    shortDescription: "Install a water-saving faucet aerator on your sink.",
    category: Category.WATER,
    difficulty: Difficulty.MEDIUM,
    points: 25,
    bonusPointsStreak: 8,
    iconEmoji: "🚰",
    bannerImageUrl: "https://picsum.photos/seed/aerator/800/400",
    proofInstructions: "Upload a photo of the installed aerator or nozzle attachment on your faucet.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "greywater-gardening",
    title: "Greywater for Plants",
    description: "Reuse non-greasy rinse water from washing vegetables, rice, or lentils to water houseplants or trees.",
    shortDescription: "Water plants using kitchen vegetable or grain rinse water.",
    category: Category.WATER,
    difficulty: Difficulty.EASY,
    points: 10,
    bonusPointsStreak: 5,
    iconEmoji: "🪴",
    bannerImageUrl: "https://picsum.photos/seed/greywater/800/400",
    proofInstructions: "Upload a photo of you pouring cooking rinse water into a potted plant or garden bed.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "turn-off-brushing-tap",
    title: "Turn Off Tap While Brushing",
    description: "Turn off the water tap completely while brushing your teeth and shaving to prevent wasted clean water.",
    shortDescription: "Keep tap tightly closed while brushing teeth.",
    category: Category.WATER,
    difficulty: Difficulty.EASY,
    points: 10,
    bonusPointsStreak: 5,
    iconEmoji: "🪥",
    bannerImageUrl: "https://picsum.photos/seed/brushtap/800/400",
    proofInstructions: "Upload a photo of your toothbrush and closed faucet at the bathroom sink.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "dual-flush-habit",
    title: "Toilet Dual-Flush Optimization",
    description: "Adjust your toilet tank displacement or install a displacement bottle to save 1 to 2 liters on every flush.",
    shortDescription: "Add a displacement bottle or tune dual flush valve.",
    category: Category.WATER,
    difficulty: Difficulty.HARD,
    points: 30,
    bonusPointsStreak: 8,
    iconEmoji: "🚽",
    bannerImageUrl: "https://picsum.photos/seed/toiletflush/800/400",
    proofInstructions: "Upload a photo of the displacement bottle or dual flush button inside the cistern.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "unplug-vampire-power",
    title: "Vampire Power Sweep",
    description: "Unplug all unused chargers, kitchen appliances, and standby electronics overnight to kill phantom loads.",
    shortDescription: "Unplug idle appliances and phone chargers at wall outlets.",
    category: Category.ENERGY,
    difficulty: Difficulty.EASY,
    points: 10,
    bonusPointsStreak: 5,
    iconEmoji: "🔌",
    bannerImageUrl: "https://picsum.photos/seed/vampirepower/800/400",
    proofInstructions: "Upload a photo showing unplugged wall adapters or switched-off power strip.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "air-dry-laundry",
    title: "Sun-Dry Your Laundry",
    description: "Skip the electric dryer and hang clothes on a drying rack or outdoor clothesline to dry naturally in the sun.",
    shortDescription: "Air-dry clothes on a clothesline or drying stand.",
    category: Category.ENERGY,
    difficulty: Difficulty.MEDIUM,
    points: 15,
    bonusPointsStreak: 5,
    iconEmoji: "🧺",
    bannerImageUrl: "https://picsum.photos/seed/clothesline/800/400",
    proofInstructions: "Upload a photo of your laundry hanging on a drying rack or outdoor line.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "ac-eco-temperature",
    title: "Eco AC Setting (24°C+)",
    description: "Set your air conditioner thermostat to 24°C (75°F) or higher and run ceiling fans for efficient cooling.",
    shortDescription: "Set air conditioning temperature to 24°C or above.",
    category: Category.ENERGY,
    difficulty: Difficulty.EASY,
    points: 15,
    bonusPointsStreak: 5,
    iconEmoji: "❄️",
    bannerImageUrl: "https://picsum.photos/seed/actemp/800/400",
    proofInstructions: "Upload a photo of your AC remote or display unit displaying 24°C or higher.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "led-bulb-swap",
    title: "Switch to LED Lighting",
    description: "Replace at least one inefficient incandescent or halogen bulb in your home with an energy-saving LED.",
    shortDescription: "Swap an old light bulb with an energy-saving LED bulb.",
    category: Category.ENERGY,
    difficulty: Difficulty.MEDIUM,
    points: 20,
    bonusPointsStreak: 6,
    iconEmoji: "💡",
    bannerImageUrl: "https://picsum.photos/seed/ledswap/800/400",
    proofInstructions: "Upload a photo of the new LED bulb or its packaging alongside the fixture.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "natural-daylight-study",
    title: "Daylight Only Workspace",
    description: "Work, read, or study next to an open window utilizing 100 percent natural sunlight without room lamps.",
    shortDescription: "Work or study using solely natural window light.",
    category: Category.ENERGY,
    difficulty: Difficulty.EASY,
    points: 10,
    bonusPointsStreak: 5,
    iconEmoji: "☀️",
    bannerImageUrl: "https://picsum.photos/seed/daylightdesk/800/400",
    proofInstructions: "Upload a photo of your illuminated daytime desk by the window with overhead lights off.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "clean-refrigerator-coils",
    title: "Clean Refrigerator Coils",
    description: "Vacuum and clean dust off your refrigerator condenser coils and check door seals to restore motor efficiency.",
    shortDescription: "Vacuum refrigerator condenser coils for higher energy efficiency.",
    category: Category.ENERGY,
    difficulty: Difficulty.HARD,
    points: 30,
    bonusPointsStreak: 10,
    iconEmoji: "🧊",
    bannerImageUrl: "https://picsum.photos/seed/fridgecoils/800/400",
    proofInstructions: "Upload a photo of the cleaned condenser grill or back panel of your refrigerator.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "smart-power-strip-setup",
    title: "Smart Power Strip Setup",
    description: "Install a master-controlled power strip or timer plug for your entertainment system or home computer desk.",
    shortDescription: "Connect your electronics to an energy-saving smart power strip.",
    category: Category.ENERGY,
    difficulty: Difficulty.HARD,
    points: 35,
    bonusPointsStreak: 10,
    iconEmoji: "⚡",
    bannerImageUrl: "https://picsum.photos/seed/powerstrip/800/400",
    proofInstructions: "Upload a photo of your newly organized power strip or smart plug managing multiple cords.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "pedal-power-commute",
    title: "Pedal Power Commute",
    description: "Ride a bicycle for your commute to work, college, or market errands instead of driving a motorized vehicle.",
    shortDescription: "Commute by bicycle for work, school, or daily errands.",
    category: Category.TRANSPORT,
    difficulty: Difficulty.MEDIUM,
    points: 25,
    bonusPointsStreak: 7,
    iconEmoji: "🚲",
    bannerImageUrl: "https://picsum.photos/seed/bicyclecommute/800/400",
    proofInstructions: "Upload a photo of your parked bicycle at your destination or bike speedometer.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "public-transit-hero",
    title: "Public Transit Hero",
    description: "Take the metro, municipal bus, or suburban train for your trip rather than booking a solo cab or driving.",
    shortDescription: "Take public bus, metro, or train for your journey.",
    category: Category.TRANSPORT,
    difficulty: Difficulty.EASY,
    points: 15,
    bonusPointsStreak: 5,
    iconEmoji: "🚌",
    bannerImageUrl: "https://picsum.photos/seed/publictransit/800/400",
    proofInstructions: "Upload a photo of your transit ticket, metro card scan, or view from inside the bus/train.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "stairway-to-health",
    title: "Skip the Elevator",
    description: "Take the stairs instead of the elevator or escalator for at least 4 flights of stairs today.",
    shortDescription: "Climb stairs instead of using elevators or escalators.",
    category: Category.TRANSPORT,
    difficulty: Difficulty.EASY,
    points: 10,
    bonusPointsStreak: 5,
    iconEmoji: "🪜",
    bannerImageUrl: "https://picsum.photos/seed/stairs/800/400",
    proofInstructions: "Upload a photo from the staircase landing or your fitness step counter.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "carpool-crew",
    title: "Carpool with Colleagues",
    description: "Share a ride with coworkers, friends, or neighbors for a shared destination to cut road emissions.",
    shortDescription: "Carpool with colleagues or neighbors for shared travel.",
    category: Category.TRANSPORT,
    difficulty: Difficulty.MEDIUM,
    points: 20,
    bonusPointsStreak: 6,
    iconEmoji: "🚗",
    bannerImageUrl: "https://picsum.photos/seed/carpool/800/400",
    proofInstructions: "Upload a group carpool selfie or rideshare carpool receipt.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "tire-pressure-tuneup",
    title: "Optimal Tire Pressure Check",
    description: "Inspect and inflate vehicle or bicycle tires to manufacturer recommended PSI to optimize fuel economy and efficiency.",
    shortDescription: "Check and inflate vehicle tires to recommended pressure.",
    category: Category.TRANSPORT,
    difficulty: Difficulty.MEDIUM,
    points: 20,
    bonusPointsStreak: 6,
    iconEmoji: "🛞",
    bannerImageUrl: "https://picsum.photos/seed/tirepressure/800/400",
    proofInstructions: "Upload a photo at the air pressure gauge or tire inflation station.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "no-idling-zone",
    title: "Zero Vehicle Idling",
    description: "Turn off your vehicle engine at traffic signals when wait time exceeds 20 seconds and while picking up passengers.",
    shortDescription: "Switch off vehicle ignition at red lights and long stops.",
    category: Category.TRANSPORT,
    difficulty: Difficulty.EASY,
    points: 10,
    bonusPointsStreak: 5,
    iconEmoji: "🛑",
    bannerImageUrl: "https://picsum.photos/seed/noidling/800/400",
    proofInstructions: "Upload a photo of your vehicle dashboard with key/ignition off at a stop.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "car-free-sunday",
    title: "100% Car-Free Day",
    description: "Go an entire 24-hour day without entering or driving any private personal car or solo motor vehicle.",
    shortDescription: "Spend an entire day moving only by walking, cycling, or transit.",
    category: Category.TRANSPORT,
    difficulty: Difficulty.HARD,
    points: 35,
    bonusPointsStreak: 10,
    iconEmoji: "👟",
    bannerImageUrl: "https://picsum.photos/seed/carfree/800/400",
    proofInstructions: "Upload a screenshot of your daily step tracking or transit pass summary.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "two-bin-segregation",
    title: "Two-Bin Waste Segregation",
    description: "Separate your daily household waste into distinct wet (organic) and dry (recyclable) bins before disposal.",
    shortDescription: "Sort household waste into distinct wet and dry bins.",
    category: Category.WASTE,
    difficulty: Difficulty.EASY,
    points: 15,
    bonusPointsStreak: 5,
    iconEmoji: "🗑️",
    bannerImageUrl: "https://picsum.photos/seed/twobin/800/400",
    proofInstructions: "Upload a photo showing side-by-side labeled wet and dry waste containers.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "refuse-plastic-straws",
    title: "Refuse Single-Use Cutlery",
    description: "Decline single-use plastic straws, spoons, forks, and ketchup sachets when ordering food or dining out.",
    shortDescription: "Say no to disposable plastic utensils and straws.",
    category: Category.WASTE,
    difficulty: Difficulty.EASY,
    points: 10,
    bonusPointsStreak: 5,
    iconEmoji: "🍴",
    bannerImageUrl: "https://picsum.photos/seed/reusablecutlery/800/400",
    proofInstructions: "Upload a photo of your reusable cutlery kit or drink enjoyed straw-free.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "balcony-composting-start",
    title: "Kitchen Scrap Composting",
    description: "Add fruit peels, coffee grounds, and vegetable ends to an indoor compost bin or terracotta composter.",
    shortDescription: "Add fresh kitchen scraps to your home compost bin.",
    category: Category.WASTE,
    difficulty: Difficulty.HARD,
    points: 35,
    bonusPointsStreak: 10,
    iconEmoji: "🪱",
    bannerImageUrl: "https://picsum.photos/seed/compostbin/800/400",
    proofInstructions: "Upload a photo of kitchen greens placed inside your active compost container.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "e-waste-dropoff",
    title: "E-Waste Collection Drop",
    description: "Gather old charging cables, dead batteries, and obsolete electronics and take them to an authorized e-waste recycler.",
    shortDescription: "Deposit old cables and electronics at an e-waste drop point.",
    category: Category.WASTE,
    difficulty: Difficulty.HARD,
    points: 40,
    bonusPointsStreak: 10,
    iconEmoji: "🔋",
    bannerImageUrl: "https://picsum.photos/seed/ewaste/800/400",
    proofInstructions: "Upload a photo of your collected e-waste at the recycling collection box.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "reusable-coffee-mug",
    title: "Bring Your Own Coffee Tumbler",
    description: "Get your morning tea, coffee, or smoothie filled in your own personal thermos or reusable tumbler.",
    shortDescription: "Use your own travel mug at a cafe or beverage kiosk.",
    category: Category.WASTE,
    difficulty: Difficulty.EASY,
    points: 15,
    bonusPointsStreak: 5,
    iconEmoji: "☕",
    bannerImageUrl: "https://picsum.photos/seed/coffeetumbler/800/400",
    proofInstructions: "Upload a photo of your beverage poured directly into your reusable thermal mug.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "mend-and-repair",
    title: "Mend It, Don't Toss It",
    description: "Sew a loose button, stitch a torn seam, or fix a household item instead of throwing it into landfill waste.",
    shortDescription: "Repair a damaged clothing item or household gadget.",
    category: Category.WASTE,
    difficulty: Difficulty.MEDIUM,
    points: 25,
    bonusPointsStreak: 7,
    iconEmoji: "🧵",
    bannerImageUrl: "https://picsum.photos/seed/mending/800/400",
    proofInstructions: "Upload a before and after photo of the mended item or stitching in progress.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "newspaper-bag-craft",
    title: "Upcycle Newspaper Bags",
    description: "Fold and glue 5 durable paper bags using discarded newspapers to replace polythene bags for dry garbage.",
    shortDescription: "Make 5 biodegradable bags from old newspapers.",
    category: Category.WASTE,
    difficulty: Difficulty.MEDIUM,
    points: 20,
    bonusPointsStreak: 6,
    iconEmoji: "📰",
    bannerImageUrl: "https://picsum.photos/seed/paperbags/800/400",
    proofInstructions: "Upload a photo of the completed newspaper trash liner bags.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "plant-based-plate",
    title: "Meatless Day Plate",
    description: "Eat all plant-based meals today with pulses, legumes, and fresh vegetables to slash personal carbon food prints.",
    shortDescription: "Eat entirely vegetarian or plant-based meals for the day.",
    category: Category.FOOD,
    difficulty: Difficulty.MEDIUM,
    points: 20,
    bonusPointsStreak: 6,
    iconEmoji: "🥗",
    bannerImageUrl: "https://picsum.photos/seed/plantplate/800/400",
    proofInstructions: "Upload a photo of your wholesome plant-based meal.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "clean-plate-hero",
    title: "Zero Plate Waste",
    description: "Serve yourself mindful portions and finish every bite on your plate without scraping leftovers into the trash.",
    shortDescription: "Leave zero food scraps behind on your plate at mealtimes.",
    category: Category.FOOD,
    difficulty: Difficulty.EASY,
    points: 10,
    bonusPointsStreak: 5,
    iconEmoji: "🍽️",
    bannerImageUrl: "https://picsum.photos/seed/cleanplate/800/400",
    proofInstructions: "Upload a photo of your completely clean plate after finishing your meal.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "shop-farmers-market",
    title: "Local Farmers Market Bounty",
    description: "Buy seasonal fruits and vegetables directly from local street vendors, organic mandis, or regional farmers.",
    shortDescription: "Buy seasonal produce from local growers or farmers market.",
    category: Category.FOOD,
    difficulty: Difficulty.MEDIUM,
    points: 20,
    bonusPointsStreak: 6,
    iconEmoji: "🥕",
    bannerImageUrl: "https://picsum.photos/seed/farmersmarket/800/400",
    proofInstructions: "Upload a photo of fresh seasonal produce purchased from a local market vendor.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "leftover-makeover",
    title: "Creative Leftover Makeover",
    description: "Transform dinner leftovers or stale bread into a delicious new breakfast or lunch recipe instead of wasting food.",
    shortDescription: "Reinvent yesterday's leftovers into a fresh meal.",
    category: Category.FOOD,
    difficulty: Difficulty.MEDIUM,
    points: 20,
    bonusPointsStreak: 6,
    iconEmoji: "🍲",
    bannerImageUrl: "https://picsum.photos/seed/leftovercooking/800/400",
    proofInstructions: "Upload a photo of your cooked reinvented leftover meal.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "grow-microgreens-window",
    title: "Window Sill Microgreens",
    description: "Sow mustard, fenugreek (methi), or wheatgrass seeds in a shallow tray and harvest your own hyper-local greens.",
    shortDescription: "Grow fresh edible microgreens on a sunny windowsill.",
    category: Category.FOOD,
    difficulty: Difficulty.HARD,
    points: 30,
    bonusPointsStreak: 8,
    iconEmoji: "🌱",
    bannerImageUrl: "https://picsum.photos/seed/microgreens/800/400",
    proofInstructions: "Upload a photo of your sprouting microgreens tray on a window sill.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "bulk-pantry-refill",
    title: "Zero-Packaging Pantry Refill",
    description: "Purchase grains, pulses, spices, or cooking oil using your own containers to avoid single-use retail plastic pouches.",
    shortDescription: "Buy grains or pulses in bulk using your own jars or cotton pouches.",
    category: Category.FOOD,
    difficulty: Difficulty.HARD,
    points: 35,
    bonusPointsStreak: 10,
    iconEmoji: "🫙",
    bannerImageUrl: "https://picsum.photos/seed/bulkrefill/800/400",
    proofInstructions: "Upload a photo of your reusable jars or tins filled at a bulk grocer.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "brew-loose-leaf",
    title: "Say No to Plastic Tea Bags",
    description: "Brew hot tea using whole loose leaves or a stainless steel infuser instead of microplastic-shedding nylon tea bags.",
    shortDescription: "Brew tea with loose tea leaves and a metal strainer.",
    category: Category.FOOD,
    difficulty: Difficulty.EASY,
    points: 10,
    bonusPointsStreak: 5,
    iconEmoji: "🫖",
    bannerImageUrl: "https://picsum.photos/seed/looseleaftea/800/400",
    proofInstructions: "Upload a photo of your stainless steel tea strainer or pot with brewed loose tea.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "neighborhood-litter-pickup",
    title: "Plogging 15-Minute Sweep",
    description: "Spend 15 minutes walking your immediate street or building perimeter collecting discarded plastic wrappers and bottles.",
    shortDescription: "Collect roadside plastic litter in a quick 15-minute sweep.",
    category: Category.COMMUNITY,
    difficulty: Difficulty.MEDIUM,
    points: 25,
    bonusPointsStreak: 7,
    iconEmoji: "🧤",
    bannerImageUrl: "https://picsum.photos/seed/plogging/800/400",
    proofInstructions: "Upload a photo of the bag of litter you collected with safety gloves.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "report-civic-pothole",
    title: "Report Civic Infrastructure Hazard",
    description: "Document a broken pavement, hazardous open drain, or streetlight fault and log it on the municipal civic app.",
    shortDescription: "File a report for a broken civic fixture or pavement pothole.",
    category: Category.COMMUNITY,
    difficulty: Difficulty.HARD,
    points: 35,
    bonusPointsStreak: 10,
    iconEmoji: "⚠️",
    bannerImageUrl: "https://picsum.photos/seed/civicreport/800/400",
    proofInstructions: "Upload a screenshot of the complaint ticket or photo of the resolved hazard spot.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "book-swap-station",
    title: "Community Book Exchange",
    description: "Donate a pre-loved book to a neighborhood little free library, school shelf, or swap one with a neighbor.",
    shortDescription: "Contribute a used book to a community exchange or friend.",
    category: Category.COMMUNITY,
    difficulty: Difficulty.EASY,
    points: 15,
    bonusPointsStreak: 5,
    iconEmoji: "📚",
    bannerImageUrl: "https://picsum.photos/seed/bookswap/800/400",
    proofInstructions: "Upload a photo of the book placed on a community shelf or handed to someone.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "eco-tip-broadcast",
    title: "Share an Eco Habit in Group Chat",
    description: "Post a practical, encouraging zero-waste or energy-saving tip in your apartment, family, or college group.",
    shortDescription: "Share a zero-waste tip in your community or society group.",
    category: Category.COMMUNITY,
    difficulty: Difficulty.EASY,
    points: 10,
    bonusPointsStreak: 5,
    iconEmoji: "💬",
    bannerImageUrl: "https://picsum.photos/seed/groupshare/800/400",
    proofInstructions: "Upload a screenshot of your shared eco-tip message in your community group.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "support-local-cobbler",
    title: "Support Local Repair Artisans",
    description: "Get your shoes, umbrella, or luggage bag serviced by a local roadside cobbler or neighborhood repair artisan.",
    shortDescription: "Get footwear or bags repaired by a local craftsperson.",
    category: Category.COMMUNITY,
    difficulty: Difficulty.MEDIUM,
    points: 25,
    bonusPointsStreak: 7,
    iconEmoji: "👞",
    bannerImageUrl: "https://picsum.photos/seed/cobblerrepair/800/400",
    proofInstructions: "Upload a photo of the repaired footwear or bag alongside the artisan's stall.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "blood-or-ration-donation",
    title: "Civic Care Donation",
    description: "Contribute surplus non-perishable groceries to a community food bank or donate blood at an accredited camp.",
    shortDescription: "Donate pantry essentials to a food bank or give blood.",
    category: Category.COMMUNITY,
    difficulty: Difficulty.HARD,
    points: 40,
    bonusPointsStreak: 10,
    iconEmoji: "🤝",
    bannerImageUrl: "https://picsum.photos/seed/communitydonation/800/400",
    proofInstructions: "Upload a photo of your donation receipt, donor badge, or dropped items.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "digital-clearing-drive",
    title: "Digital Carbon Declutter",
    description: "Delete 200 obsolete emails, junk files, and cloud backups to reduce energy consumption in remote server datacenters.",
    shortDescription: "Delete 200 junk emails or duplicate cloud photos.",
    category: Category.COMMUNITY,
    difficulty: Difficulty.EASY,
    points: 10,
    bonusPointsStreak: 5,
    iconEmoji: "📧",
    bannerImageUrl: "https://picsum.photos/seed/digitalclean/800/400",
    proofInstructions: "Upload a screenshot showing emptied trash/spam mailbox folder.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "mentor-eco-junior",
    title: "Youth Eco Mentorship",
    description: "Teach a child, sibling, or student how to segregate waste, nurture a plant, or conserve clean drinking water.",
    shortDescription: "Teach a young person a core environmental practice.",
    category: Category.COMMUNITY,
    difficulty: Difficulty.MEDIUM,
    points: 20,
    bonusPointsStreak: 6,
    iconEmoji: "🧑‍🏫",
    bannerImageUrl: "https://picsum.photos/seed/ecomentor/800/400",
    proofInstructions: "Upload a photo of your hands-on teaching activity or drawing with the student.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "plant-a-native-sapling",
    title: "Plant a Native Tree or Shrub",
    description: "Plant an indigenous sapling like neem, tulsi, peepal, or hibiscus in soil that you promise to nurture weekly.",
    shortDescription: "Plant a native tree or flowering shrub in soil.",
    category: Category.NATURE,
    difficulty: Difficulty.HARD,
    points: 35,
    bonusPointsStreak: 10,
    iconEmoji: "🌳",
    bannerImageUrl: "https://picsum.photos/seed/nativesapling/800/400",
    proofInstructions: "Upload a photo of your newly planted sapling firmly set in soil.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "bird-water-feeder",
    title: "Earthen Bird Water Bowl",
    description: "Place a shallow clay bowl of clean freshwater on your terrace, balcony, or garden for thirsty urban birds.",
    shortDescription: "Set up a clean water bath or bowl for neighborhood birds.",
    category: Category.NATURE,
    difficulty: Difficulty.EASY,
    points: 15,
    bonusPointsStreak: 5,
    iconEmoji: "🐦",
    bannerImageUrl: "https://picsum.photos/seed/birdwater/800/400",
    proofInstructions: "Upload a photo of your filled water bowl placed outside for visiting birds.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "urban-nature-spotting",
    title: "Document Urban Biodiversity",
    description: "Spot and identify 3 wild bird, insect, or plant species in your neighborhood and log them in a biodiversity journal.",
    shortDescription: "Photograph and identify 3 local urban wildlife species.",
    category: Category.NATURE,
    difficulty: Difficulty.MEDIUM,
    points: 20,
    bonusPointsStreak: 6,
    iconEmoji: "🔍",
    bannerImageUrl: "https://picsum.photos/seed/biodiversity/800/400",
    proofInstructions: "Upload a photo collage or picture of the species you spotted outdoors.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "organic-mulching",
    title: "Mulch with Dry Fallen Leaves",
    description: "Collect dry fallen leaves and spread them around tree bases or garden beds to retain soil moisture and prevent burning.",
    shortDescription: "Mulch garden beds or tree bases with dry fallen leaves.",
    category: Category.NATURE,
    difficulty: Difficulty.MEDIUM,
    points: 20,
    bonusPointsStreak: 6,
    iconEmoji: "🍂",
    bannerImageUrl: "https://picsum.photos/seed/leafmulch/800/400",
    proofInstructions: "Upload a photo of tree roots or potted soil covered in organic leaf mulch.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "pollinator-friendly-pot",
    title: "Plant for Pollinators",
    description: "Add a nectar-rich flowering plant like marigold, zinnia, or basil to support local honeybees and butterflies.",
    shortDescription: "Grow a nectar-rich flowering plant for bees and butterflies.",
    category: Category.NATURE,
    difficulty: Difficulty.MEDIUM,
    points: 20,
    bonusPointsStreak: 6,
    iconEmoji: "🐝",
    bannerImageUrl: "https://picsum.photos/seed/pollinatorflowers/800/400",
    proofInstructions: "Upload a photo of your flowering plant positioned in an open sunlit spot.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "adopt-a-street-tree",
    title: "Water a Street Tree",
    description: "Adopt and give two full buckets of water to a struggling young street tree outside your home or office.",
    shortDescription: "Water and clear weeds around a neighborhood street tree.",
    category: Category.NATURE,
    difficulty: Difficulty.EASY,
    points: 15,
    bonusPointsStreak: 5,
    iconEmoji: "🪴",
    bannerImageUrl: "https://picsum.photos/seed/streettree/800/400",
    proofInstructions: "Upload a photo of you watering the base of the roadside tree.",
    isDaily: true,
    isActive: true
  },
  {
    challengeId: "zero-chemical-garden",
    title: "Natural Pest Control Spray",
    description: "Mix an organic neem oil or soap-water spray to treat garden pests instead of spraying toxic chemical pesticides.",
    shortDescription: "Use homemade neem spray for natural organic plant care.",
    category: Category.NATURE,
    difficulty: Difficulty.HARD,
    points: 30,
    bonusPointsStreak: 8,
    iconEmoji: "🌿",
    bannerImageUrl: "https://picsum.photos/seed/neemspray/800/400",
    proofInstructions: "Upload a photo of your organic spray bottle beside your treated garden plants.",
    isDaily: true,
    isActive: true
  }
];

const events = [
  {
    eventId: "clean-up-drive-juhu",
    title: "Juhu Beach Clean-up Drive 2026",
    description: "Join us for a massive beach clean-up drive at Juhu Beach. Let's make our coastline plastic-free!",
    eventType: "CLEAN_UP_DRIVE",
    status: "UPCOMING",
    startDate: "2026-03-28T07:00:00Z",
    endDate: "2026-03-28T11:00:00Z",
    location: {
      venueName: "Juhu Beach",
      city: "Mumbai",
      country: "India"
    },
    bonusPoints: 50,
    bannerImageUrl: "https://picsum.photos/seed/cleanup/1200/600"
  }
];

export async function seedChallenges() {
  const batch = writeBatch(db);
  
  // Seed Challenges
  challenges.forEach((challenge) => {
    const ref = doc(collection(db, "challenges"), challenge.challengeId);
    batch.set(ref, challenge);
  });

  // Seed Events
  events.forEach((event) => {
    const ref = doc(collection(db, "events"), event.eventId);
    batch.set(ref, event);
  });

  await batch.commit();

  // Seed Admin User (if not exists)
  // Note: In real app, you'd do this via admin panel or script
  console.log("Seed data populated successfully!");
}

